version: '3'

services:
  postgres:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - ../docker/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "25432:5432"

  rabbit:
    restart: always
    image: rabbitmq:3.10.6-management
    ports:
      - '15672:15672'
      - '5672:5672'

networks:
  otus-network:
    driver: bridge
